// Gangfolge 60486-11
const GANGFOLGE_11_ROUTE = [
  ["Rödelheimer Landstr.","58"],
  ["Rödelheimer Landstr.","54-56"],
  ["Rödelheimer Landstr.","52"],
  ["Rödelheimer Landstr.","50"],
  ["Rödelheimer Landstr.","19"],
  ["Rödelheimer Landstr.","17"],
  ["Rödelheimer Landstr.","17a"],
  ["Rödelheimer Landstr.","15a"],
  ["Rödelheimer Landstr.","15"],
  ["Karoline-Veith-Str.","7"],
  ["Karoline-Veith-Str.","9"],
  ["Karoline-Veith-Str.","35"],
  ["Karoline-Veith-Str.","37"],
  ["Karoline-Veith-Str.","33"],
  ["Karoline-Veith-Str.","31"],
  ["Karoline-Veith-Str.","29"],
  ["Karoline-Veith-Str.","27"],
  ["Karoline-Veith-Str.","25"],
  ["Karoline-Veith-Str.","23"],
  ["Karoline-Veith-Str.","21"],
  ["Karoline-Veith-Str.","19"],
  ["Karoline-Veith-Str.","17"],
  ["Karoline-Veith-Str.","15"],
  ["Karoline-Veith-Str.","13"],
  ["Karoline-Veith-Str.","11"],
  ["Karoline-Veith-Str.","1"],
  ["Karoline-Veith-Str.","3"],
  ["Karoline-Veith-Str.","5"],
  ["Rödelheimer Landstr.","11a"],
  ["Rödelheimer Landstr.","11"],
  ["Rödelheimer Landstr.","9a"],
  ["Rödelheimer Landstr.","9"],
  ["Rödelheimer Landstr.","7"],
  ["Rödelheimer Landstr.","7a"],
  ["Rödelheimer Landstr.","13"],
  ["Rödelheimer Landstr.","13a"],
  ["Rödelheimer Landstr.","13b"],
  ["Rödelheimer Landstr.","44"],
  ["Rödelheimer Landstr.","42"],
  ["Rödelheimer Landstr.","40"],
  ["Rödelheimer Landstr.","40a"],
  ["Rödelheimer Landstr.","38"],
  ["Rödelheimer Landstr.","36"],
  ["Rödelheimer Landstr.","34"],
  ["Rödelheimer Landstr.","32"],
  ["Rödelheimer Landstr.","30b"],
  ["Rödelheimer Landstr.","30a"],
  ["Rödelheimer Landstr.","30"],
  ["Rödelheimer Landstr.","28-28a"],
  ["Rödelheimer Landstr.","28a"],
  ["Rödelheimer Landstr.","26"],
  ["Goldina-Hirschberg-Str.","2"],
  ["Goldina-Hirschberg-Str.","4"],
  ["Goldina-Hirschberg-Str.","1"],
  ["Goldina-Hirschberg-Str.","3"],
  ["Goldina-Hirschberg-Str.","5"],
  ["Goldina-Hirschberg-Str.","7"],
  ["Goldina-Hirschberg-Str.","9"],
  ["Goldina-Hirschberg-Str.","11"],
  ["Goldina-Hirschberg-Str.","13"],
  ["Goldina-Hirschberg-Str.","15"],
  ["Goldina-Hirschberg-Str.","17"],
  ["Brigitte-Frauendorf-Str.","40"],
  ["Brigitte-Frauendorf-Str.","38"],
  ["Brigitte-Frauendorf-Str.","36"],
  ["Brigitte-Frauendorf-Str.","34"],
  ["Brigitte-Frauendorf-Str.","32"],
  ["Brigitte-Frauendorf-Str.","11"],
  ["Brigitte-Frauendorf-Str.","9"],
  ["Brigitte-Frauendorf-Str.","30"],
  ["Brigitte-Frauendorf-Str.","7"],
  ["Brigitte-Frauendorf-Str.","28"],
  ["Brigitte-Frauendorf-Str.","26"],
  ["Brigitte-Frauendorf-Str.","24"],
  ["Brigitte-Frauendorf-Str.","22"],
  ["Brigitte-Frauendorf-Str.","20"],
  ["Brigitte-Frauendorf-Str.","1"],
  ["Kasernenstr.","10"],
  ["Kasernenstr.","12"],
  ["Brigitte-Frauendorf-Str.","18"],
  ["Brigitte-Frauendorf-Str.","16"],
  ["Brigitte-Frauendorf-Str.","14"],
  ["Brigitte-Frauendorf-Str.","12"],
  ["Brigitte-Frauendorf-Str.","10"],
  ["Brigitte-Frauendorf-Str.","8"],
  ["Brigitte-Frauendorf-Str.","6"],
  ["Brigitte-Frauendorf-Str.","4"],
  ["Brigitte-Frauendorf-Str.","2"],
  ["Rödelheimer Landstr.","1"],
  ["Rödelheimer Landstr.","3"],
  ["Rödelheimer Landstr.","5"],
  ["Rödelheimer Landstr.","5a"],
  ["Rödelheimer Landstr.","24"],
  ["Rödelheimer Landstr.","22"],
  ["Rödelheimer Landstr.","20"],
  ["Rödelheimer Landstr.","16"],
  ["Rödelheimer Landstr.","14"],
  ["Rödelheimer Landstr.","12"],
  ["Rödelheimer Landstr.","10"],
  ["Rödelheimer Landstr.","8"],
  ["Rödelheimer Landstr.","6a"],
  ["Rödelheimer Landstr.","6"],
  ["Rödelheimer Landstr.","4"],
  ["Rödelheimer Str.","38"],
  ["Rödelheimer Str.","34c"],
  ["Rödelheimer Str.","34b"],
  ["Rödelheimer Str.","34a"],
  ["Rödelheimer Str.","34"],
  ["Rödelheimer Str.","32"],
  ["Rödelheimer Str.","36"],
  ["Rödelheimer Str.","45"],
  ["Rödelheimer Str.","49"],
  ["Salvador-Allende-Str.","11"],
  ["Salvador-Allende-Str.","9"],
  ["Salvador-Allende-Str.","7"],
  ["Salvador-Allende-Str.","5"],
  ["Salvador-Allende-Str.","3"],
  ["Salvador-Allende-Str.","1"],
  ["Kasseler Str.","1a"],
  ["Kasseler Str.","1c"],
  ["Hersfelder Str.","25"],
  ["Hersfelder Str.","23"],
  ["Hersfelder Str.","21"],
  ["Hersfelder Str.","19"],
  ["Hersfelder Str.","17"],
  ["Schönhofstr.","18"],
  ["Schönhofstr.","20"],
  ["Schönhofstr.","22"],
  ["Schönhofstr.","24"],
  ["Schönhofstr.","26"],
  ["Schönhofstr.","28"],
  ["Schönhofstr.","30"],
  ["Schönhofstr.","25"],
  ["Schönhofstr.","23"],
  ["Schönhofstr.","21"],
  ["Schönhofstr.","19"],
  ["Hersfelder Str.","13"],
  ["Hersfelder Str.","11"],
  ["Hersfelder Str.","9"],
  ["Hersfelder Str.","3"],
  ["Hersfelder Str.","1"],
  ["Hersfelder Str.","6"],
  ["Hersfelder Str.","8"],
  ["Schönhofstr.","17"],
  ["Schönhofstr.","9"],
  ["Schönhofstr.","7"],
  ["Schönhofstr.","2-4"],
  ["Schönhofstr.","8a"],
  ["Schönhofstr.","6a"],
  ["Schönhofstr.","6-8"],
  ["Schönhofstr.","10"],
  ["Schönhofstr.","12"],
  ["Schönhofstr.","14"],
  ["Hersfelder Str.","10"],
  ["Hersfelder Str.","12"],
  ["Hersfelder Str.","14"],
  ["Salvador-Allende-Str.","12"],
  ["Salvador-Allende-Str.","14"],
  ["Salvador-Allende-Str.","16"],
  ["Rödelheimer Str.","37"],
  ["Rödelheimer Str.","35"],
  ["Rödelheimer Str.","33"],
  ["Rödelheimer Str.","31"],
  ["Schloßstr.","10"],
  ["Schloßstr.","12"],
  ["Schloßstr.","14"],
  ["Schloßstr.","16"],
  ["Schloßstr.","18"],
  ["Schloßstr.","20"],
  ["Schloßstr.","22"],
  ["Schloßstr.","24"],
  ["Schloßstr.","26"],
  ["Schloßstr.","28"],
  ["Schloßstr.","30"],
  ["Schloßstr.","32"],
  ["Schloßstr.","34"],
  ["Schloßstr.","38"],
  ["Schloßstr.","40"],
  ["Schloßstr.","42"],
  ["Ederstr.","2"],
  ["Ederstr.","8"],
  ["Ederstr.","10"],
  ["Werrastr.","34"],
  ["Werrastr.","36"],
  ["Werrastr.","38"],
  ["Werrastr.","40"],
  ["Werrastr.","42"],
  ["Werrastr.","41"],
  ["Werrastr.","39a"],
  ["Ederstr.","12"],
  ["Ederstr.","14"],
  ["Kasseler Str.","2"],
  ["Kasseler Str.","7"],
  ["Kasseler Str.","17a"],
  ["Kasseler Str.","17"],
  ["Kasseler Str.","15"],
  ["Kasseler Str.","13"],
  ["Kasseler Str.","11"],
  ["Kurfürstenstr.","57"],
  ["Kurfürstenstr.","55"],
  ["Kurfürstenstr.","53"],
  ["Kurfürstenstr.","60"],
  ["Kasseler Str.","3"],
  ["Ederstr.","15"],
  ["Ederstr.","13"],
  ["Ederstr.","11"],
  ["Ederstr.","9"],
  ["Werrastr.","30"],
  ["Werrastr.","28"],
  ["Werrastr.","26"],
  ["Werrastr.","24"],
  ["Werrastr.","22"],
  ["Werrastr.","20"],
  ["Werrastr.","27-29"],
  ["Werrastr.","25"],
  ["Werrastr.","21"],
  ["Werrastr.","19"],
  ["Werrastr.","17"],
  ["Werrastr.","15"],
  ["Werrastr.","13"],
  ["Werrastr.","7"],
  ["Werrastr.","5"],
  ["Werrastr.","3"],
  ["Werrastr.","2"],
  ["Werrastr.","4"],
  ["Werrastr.","6"],
  ["Kurfürstenstr.","49"],
  ["Werrastr.","16"],
  ["Werrastr.","18"],
  ["Kurfürstenstr.","47"],
  ["Kurfürstenstr.","45"],
  ["Schloßstr.","58"],
  ["Schloßstr.","56"],
  ["Schloßstr.","54"],
  ["Schloßstr.","52"],
  ["Schloßstr.","50"],
  ["Schloßstr.","48"],
  ["Schloßstr.","46"],
  ["Schloßstr.","41"],
  ["Schloßstr.","39"],
  ["Schloßstr.","37"],
  ["Schloßstr.","35a"],
  ["Schloßstr.","35"],
  ["Mühlgasse","31"],
  ["Mühlgasse","29"],
  ["Schwälmer Str.","2"],
  ["Schwälmer Str.","4"],
  ["Schwälmer Str.","6"],
  ["Schwälmer Str.","8"],
  ["Schwälmer Str.","10"],
  ["Schwälmer Str.","12"],
  ["Schwälmer Str.","14"],
  ["Schwälmer Str.","20"],
  ["Schwälmer Str.","22"],
  ["Schwälmer Str.","24"],
  ["Schwälmer Str.","26"],
  ["Schwälmer Str.","28"],
  ["Schwälmer Str.","21"],
  ["Schwälmer Str.","19"],
  ["Schwälmer Str.","17"],
  ["Schwälmer Str.","15"],
  ["Schwälmer Str.","13"],
  ["Schwälmer Str.","11"],
  ["Schwälmer Str.","9"],
  ["Schwälmer Str.","5"],
  ["Schwälmer Str.","1"],
  ["Schwälmer Str.","3"],
  ["Schwälmer Str.","7"],
  ["Große Seestr.","2"],
  ["Große Seestr.","4"],
  ["Große Seestr.","6"],
  ["Große Seestr.","8"],
  ["Große Seestr.","10"],
  ["Große Seestr.","12"],
  ["Große Seestr.","14"],
  ["Große Seestr.","16"],
  ["Große Seestr.","18"],
  ["Große Seestr.","23"],
  ["Große Seestr.","21"],
  ["Große Seestr.","19"],
  ["Große Seestr.","17"],
  ["Große Seestr.","15"],
  ["Große Seestr.","13"],
  ["Große Seestr.","11"],
  ["Große Seestr.","9"],
  ["Große Seestr.","7"],
  ["Große Seestr.","5"],
  ["Große Seestr.","3"],
  ["Große Seestr.","1"],
  ["Mühlgasse","13"],
  ["Mühlgasse","11"],
  ["Mühlgasse","7"],
  ["Otto-Loewe-Str.","2a"],
  ["Otto-Loewe-Str.","2b"],
  ["Otto-Loewe-Str.","4"],
  ["Otto-Loewe-Str.","6"],
  ["Otto-Loewe-Str.","8"],
  ["Otto-Loewe-Str.","10"],
  ["Otto-Loewe-Str.","12"],
  ["Otto-Loewe-Str.","5"],
  ["Otto-Loewe-Str.","3"],
  ["Otto-Loewe-Str.","1"],
  ["Mühlgasse","3a"],
  ["Mühlgasse","3"],
  ["Mühlgasse","1"],
  ["Mühlgasse","8-12"],
  ["Mühlgasse","18"],
  ["Mühlgasse","20"],
  ["Mühlgasse","22"],
  ["Mühlgasse","24"],
  ["Mühlgasse","26"],
  ["Mühlgasse","28"],
  ["Schloßstr.","29"],
  ["Schloßstr.","25"],
  ["Schloßstr.","23"],
  ["Schloßstr.","21"],
  ["Schloßstr.","19"],
  ["Schloßstr.","17"],
  ["Schloßstr.","13-15"],
  ["Schloßstr.","11"],
  ["Schloßstr.","9"],
  ["Schloßstr.","7"],
  ["Schloßstr.","5"],
];

const GANGFOLGE_11_ALIASES = {
  "rödelheimer landstrasse":"Rödelheimer Landstr.","rödelheimer landstr":"Rödelheimer Landstr.",
  "roedelheimer landstrasse":"Rödelheimer Landstr.","roedelheimer landstr":"Rödelheimer Landstr.",
  "rödelheimer strasse":"Rödelheimer Str.","rödelheimer str":"Rödelheimer Str.",
  "roedelheimer strasse":"Rödelheimer Str.",
  "karoline veith strasse":"Karoline-Veith-Str.","karoline veith":"Karoline-Veith-Str.","veith":"Karoline-Veith-Str.",
  "goldina hirschberg strasse":"Goldina-Hirschberg-Str.","hirschberg":"Goldina-Hirschberg-Str.",
  "brigitte frauendorf strasse":"Brigitte-Frauendorf-Str.","frauendorf":"Brigitte-Frauendorf-Str.",
  "kasernenstrasse":"Kasernenstr.","kasernenstr":"Kasernenstr.",
  "kasseler strasse":"Kasseler Str.","kasseler str":"Kasseler Str.",
  "hersfelder strasse":"Hersfelder Str.","hersfelder str":"Hersfelder Str.",
  "schönhofstrasse":"Schönhofstr.","schoenhofstrasse":"Schönhofstr.",
  "salvador allende strasse":"Salvador-Allende-Str.","salvador allende":"Salvador-Allende-Str.","allende":"Salvador-Allende-Str.",
  "schlosstrasse":"Schloßstr.","schlossstr":"Schloßstr.","schloßstr":"Schloßstr.",
  "ederstrasse":"Ederstr.","ederstr":"Ederstr.",
  "werrastrasse":"Werrastr.","werrastr":"Werrastr.",
  "kurfürstenstrasse":"Kurfürstenstr.","kurfuerstenstrasse":"Kurfürstenstr.",
  "mühlgasse":"Mühlgasse","muehlgasse":"Mühlgasse",
  "schwälmer strasse":"Schwälmer Str.","schwaelmer strasse":"Schwälmer Str.",
  "große seestrasse":"Große Seestr.","grosse seestrasse":"Große Seestr.",
  "otto loewe strasse":"Otto-Loewe-Str.","otto loewe":"Otto-Loewe-Str.","loewe":"Otto-Loewe-Str.",
  "otto löwe strasse":"Otto-Loewe-Str.","otto löwe":"Otto-Loewe-Str.","löwe":"Otto-Loewe-Str.",
  "otto löbe strasse":"Otto-Loewe-Str.","otto löbe":"Otto-Loewe-Str.","löbe":"Otto-Loewe-Str.",
  "otto loebe":"Otto-Loewe-Str.","loebe":"Otto-Loewe-Str."
};


  registerGangfolge({
    name: '60486-11',
    route: GANGFOLGE_11_ROUTE,
    aliases: GANGFOLGE_11_ALIASES
  });