// Gangfolge 60488-06
const GANGFOLGE_06_ROUTE = [
  ["Ludwig-Landmann-Str.","219"],
  ["Ludwig-Landmann-Str.","210"],
  ["Ludwig-Landmann-Str.","212"],
  ["Ludwig-Landmann-Str.","212"],
  ["Ludwig-Landmann-Str.","214"],
  ["Ludwig-Landmann-Str.","216"],
  ["Stephan-Heise-Str.","1"],
  ["Stephan-Heise-Str.","3"],
  ["Stephan-Heise-Str.","5"],
  ["Stephan-Heise-Str.","7"],
  ["Stephan-Heise-Str.","9"],
  ["Stephan-Heise-Str.","11"],
  ["Stephan-Heise-Str.","13"],
  ["Stephan-Heise-Str.","15"],
  ["Stephan-Heise-Str.","4"],
  ["Stephan-Heise-Str.","6"],
  ["Stephan-Heise-Str.","8"],
  ["Stephan-Heise-Str.","10"],
  ["Stephan-Heise-Str.","12"],
  ["Stephan-Heise-Str.","14"],
  ["Stephan-Heise-Str.","16"],
  ["Stephan-Heise-Str.","30"],
  ["Stephan-Heise-Str.","28"],
  ["Stephan-Heise-Str.","26"],
  ["Stephan-Heise-Str.","24"],
  ["Stephan-Heise-Str.","22"],
  ["Stephan-Heise-Str.","20"],
  ["Stephan-Heise-Str.","18"],
  ["Stephan-Heise-Str.","17"],
  ["Stephan-Heise-Str.","19"],
  ["Stephan-Heise-Str.","27"],
  ["Stephan-Heise-Str.","25"],
  ["Stephan-Heise-Str.","23"],
  ["Stephan-Heise-Str.","21"],
  ["Westring","20"],
  ["Westring","22"],
  ["Westring","24"],
  ["Stephan-Heise-Str.","35"],
  ["Stephan-Heise-Str.","37"],
  ["Stephan-Heise-Str.","39"],
  ["Stephan-Heise-Str.","41"],
  ["Stephan-Heise-Str.","33"],
  ["Stephan-Heise-Str.","31"],
  ["Stephan-Heise-Str.","29"],
  ["Stephan-Heise-Str.","32"],
  ["Stephan-Heise-Str.","34"],
  ["Stephan-Heise-Str.","36"],
  ["Stephan-Heise-Str.","38"],
  ["Stephan-Heise-Str.","40"],
  ["Stephan-Heise-Str.","42"],
  ["Stephan-Heise-Str.","44"],
  ["Stephan-Heise-Str.","58"],
  ["Stephan-Heise-Str.","56"],
  ["Stephan-Heise-Str.","54"],
  ["Stephan-Heise-Str.","52"],
  ["Stephan-Heise-Str.","50"],
  ["Stephan-Heise-Str.","48"],
  ["Stephan-Heise-Str.","46"],
  ["Stephan-Heise-Str.","60"],
  ["Stephan-Heise-Str.","62"],
  ["Stephan-Heise-Str.","64"],
  ["Stephan-Heise-Str.","66"],
  ["Stephan-Heise-Str.","68"],
  ["Stephan-Heise-Str.","70"],
  ["Stephan-Heise-Str.","72"],
  ["Stephan-Heise-Str.","86"],
  ["Stephan-Heise-Str.","84"],
  ["Stephan-Heise-Str.","82"],
  ["Stephan-Heise-Str.","80"],
  ["Stephan-Heise-Str.","78"],
  ["Stephan-Heise-Str.","76"],
  ["Stephan-Heise-Str.","74"],
  ["Stephan-Heise-Str.","43"],
  ["Stephan-Heise-Str.","45"],
  ["Stephan-Heise-Str.","47"],
  ["Stephan-Heise-Str.","49"],
  ["Stephan-Heise-Str.","51"],
  ["Stephan-Heise-Str.","53"],
  ["Stephan-Heise-Str.","55"],
  ["Stephan-Heise-Str.","102"],
  ["Stephan-Heise-Str.","88"],
  ["Stephan-Heise-Str.","90"],
  ["Stephan-Heise-Str.","92"],
  ["Stephan-Heise-Str.","94"],
  ["Stephan-Heise-Str.","96"],
  ["Stephan-Heise-Str.","98"],
  ["Stephan-Heise-Str.","100"],
  ["Stephan-Heise-Str.","114"],
  ["Stephan-Heise-Str.","112"],
  ["Stephan-Heise-Str.","110"],
  ["Stephan-Heise-Str.","108"],
  ["Stephan-Heise-Str.","106"],
  ["Stephan-Heise-Str.","104"],
  ["Kollwitzstr.","3"],
  ["Kollwitzstr.","3"],
  ["Gontardstr.","11"],
  ["Gontardstr.","11"],
  ["Reifenberger Str.","75"],
  ["Reifenberger Str.","73"],
  ["Reifenberger Str.","73"],
  ["Kollwitzstr.","1"],
  ["Westring","54"],
  ["Westring","52"],
  ["Westring","50"],
  ["Westring","48"],
  ["Westring","46"],
  ["Westring","44"],
  ["Westring","44"],
  ["Westring","44"],
  ["Westring","44"],
  ["Westring","39"],
  ["Westring","37"],
  ["Westring","35"],
  ["Westring","33"],
  ["Westring","31"],
  ["Westring","29"],
  ["Westring","27"],
  ["Westring","25"],
  ["Westring","23"],
  ["Westring","21"],
  ["Westring","19"],
  ["Westring","17"],
  ["Westring","15"],
  ["Westring","12"],
  ["Westring","10"],
  ["Westring","13"],
  ["Westring","11"],
  ["Westring","6"],
  ["Westring","2"],
  ["Ludwig-Landmann-Str.","304"],
  ["Ludwig-Landmann-Str.","306"],
  ["Ludwig-Landmann-Str.","308"],
  ["Ludwig-Landmann-Str.","310"],
  ["Ludwig-Landmann-Str.","312"],
  ["Hausener Weg","55"],
  ["Hausener Weg","57"],
  ["Hausener Weg","59"],
  ["Hausener Weg","61"],
  ["Hausener Weg","120"],
  ["Hausener Weg","120"],
  ["Hausener Weg","120"],
  ["Hausener Weg","63"],
  ["Hausener Weg","65"],
  ["Hausener Weg","116"],
  ["Hausener Weg","116"],
  ["Hausener Weg","114"],
  ["Hausener Weg","112"],
  ["Hausener Weg","112a"],
  ["Ludwig-Landmann-Str.","339"],
  ["Hausener Weg","41"],
  ["Hausener Weg","39"],
  ["Hausener Weg","37"],
  ["Hausener Weg","35"],
  ["Hausener Weg","33"],
  ["Hausener Weg","29"],
  ["Hausener Weg","29"],
  ["Hausener Weg","31"],
  ["Hausener Weg","27"],
  ["Hausener Weg","27a"],
  ["Hausener Weg","27b"],
  ["Schmittener Str.","1"],
  ["Schmittener Str.","3"],
  ["Schmittener Str.","5"],
  ["Schmittener Str.","7"],
  ["Schmittener Str.","9"],
  ["Schmittener Str.","11"],
  ["Schmittener Str.","21"],
  ["Schmittener Str.","23"],
  ["Schmittener Str.","25"],
  ["Schmittener Str.","27"],
  ["Schmittener Str.","29"],
  ["Schmittener Str.","24"],
  ["Schmittener Str.","22"],
  ["Schmittener Str.","20"],
  ["Schmittener Str.","18"],
  ["Schmittener Str.","12"],
  ["Schmittener Str.","10"],
  ["Niddagaustr.","88"],
  ["Niddagaustr.","86"],
  ["Niddagaustr.","84"],
  ["Niddagaustr.","82"],
  ["Niddagaustr.","69"],
  ["Niddagaustr.","71"],
  ["Niddagaustr.","73"],
  ["Niddagaustr.","75-77"],
  ["Niddagaustr.","79"],
  ["Niddagaustr.","81"],
  ["Niddagaustr.","85"],
  ["Niddagaustr.","87"],
  ["Niddagaustr.","87a"],
  ["Niddagaustr.","89"],
  ["Niddagaustr.","91"],
  ["Niddagaustr.","95"],
  ["Niddagaustr.","97"],
  ["Niddagaustr.","96"],
  ["Niddagaustr.","94"],
  ["Niddagaustr.","92"],
  ["Alexanderstr.","97"],
  ["Seelenberger Str.","15"],
  ["Seelenberger Str.","19"],
  ["Seelenberger Str.","21"],
  ["Seelenberger Str.","2"],
  ["Seelenberger Str.","4"],
  ["Seelenberger Str.","6"],
  ["Seelenberger Str.","6a"],
  ["Seelenberger Str.","4a"],
  ["Seelenberger Str.","8"],
  ["Seelenberger Str.","10"],
  ["Seelenberger Str.","23"],
  ["Seelenberger Str.","25"],
  ["Seelenberger Str.","27"],
  ["Seelenberger Str.","29"],
  ["Fuchstanzstr.","144"],
  ["Fuchstanzstr.","146"],
  ["Fuchstanzstr.","148"],
  ["Fuchstanzstr.","150"],
  ["Fuchstanzstr.","152"],
  ["Fuchstanzstr.","154"],
  ["Fuchstanzstr.","154a"],
  ["Fuchstanzstr.","147"],
  ["Fuchstanzstr.","149"],
  ["Fuchstanzstr.","151"],
  ["Fuchstanzstr.","153"],
  ["Fuchstanzstr.","139"],
  ["Fuchstanzstr.","141"],
  ["Fuchstanzstr.","143"],
  ["Fuchstanzstr.","145"],
  ["Fuchstanzstr.","131"],
  ["Fuchstanzstr.","133"],
  ["Fuchstanzstr.","135"],
  ["Fuchstanzstr.","137"],
  ["Fuchstanzstr.","123"],
  ["Fuchstanzstr.","125"],
  ["Fuchstanzstr.","127"],
  ["Fuchstanzstr.","129"],
  ["Fuchstanzstr.","140"],
  ["Fuchstanzstr.","136"],
  ["Fuchstanzstr.","115"],
  ["Fuchstanzstr.","117"],
  ["Fuchstanzstr.","119"],
  ["Fuchstanzstr.","121"],
  ["Fuchstanzstr.","134"],
  ["Fuchstanzstr.","132"],
  ["Fuchstanzstr.","113"],
  ["Fuchstanzstr.","130a"],
  ["Fuchstanzstr.","111"],
  ["Fuchstanzstr.","130"],
  ["Fuchstanzstr.","128"],
  ["Fuchstanzstr.","126"],
  ["Fuchstanzstr.","109"],
  ["Fuchstanzstr.","107"],
  ["Fuchstanzstr.","124"],
  ["Fuchstanzstr.","122"],
  ["Fuchstanzstr.","120"],
  ["Hattsteiner Str.","26"],
  ["Hattsteiner Str.","24"],
  ["Hattsteiner Str.","22"],
  ["Hattsteiner Str.","20"],
  ["Hattsteiner Str.","18"],
  ["Hattsteiner Str.","16"],
  ["Hattsteiner Str.","19"],
  ["Hattsteiner Str.","21"],
  ["Hattsteiner Str.","23a"],
  ["Hattsteiner Str.","23"],
  ["Hattsteiner Str.","25"],
  ["Hattsteiner Str.","27"],
  ["Hattsteiner Str.","29"],
  ["Fuchstanzstr.","84"],
  ["Fuchstanzstr.","82"],
  ["Fuchstanzstr.","80"],
  ["Fuchstanzstr.","78"],
  ["Fuchstanzstr.","76"],
  ["Fuchstanzstr.","74"],
  ["Fuchstanzstr.","72"],
  ["Fuchstanzstr.","83"],
  ["Fuchstanzstr.","83a"],
  ["Fuchstanzstr.","85"],
  ["Fuchstanzstr.","87"],
  ["Fuchstanzstr.","89"],
  ["Fuchstanzstr.","91"],
  ["Fuchstanzstr.","93"],
  ["Fuchstanzstr.","95"],
  ["Fuchstanzstr.","97"],
  ["Fuchstanzstr.","99"],
  ["Fuchstanzstr.","101"],
  ["Fuchstanzstr.","103"],
  ["Fuchstanzstr.","105"],
  ["Fuchstanzstr.","105a"],
  ["Reichenbecher Weg","1"],
  ["Reinbomer Weg","38"],
  ["Reinbomer Weg","34"],
  ["Reinbomer Weg","32"],
  ["Reinbomer Weg","30"],
  ["Reinbomer Weg","28"],
  ["Reinbomer Weg","26"],
  ["Reinbomer Weg","22"],
  ["Reinbomer Weg","14"],
  ["Reinbomer Weg","12"],
  ["Reinbomer Weg","10"],
  ["Reinbomer Weg","4"],
  ["Reinbomer Weg","2"],
  ["Reifenberger Str.","63"],
  ["Reifenberger Str.","61"],
  ["Reifenberger Str.","59"],
  ["Reifenberger Str.","57"],
  ["Fuchstanzstr.","81a"],
  ["Fuchstanzstr.","81"],
  ["Fuchstanzstr.","79"],
  ["Fuchstanzstr.","77"],
  ["Fuchstanzstr.","75"],
  ["Fuchstanzstr.","73"],
  ["Fuchstanzstr.","71"],
  ["Fuchstanzstr.","69"],
  ["Fuchstanzstr.","67"],
  ["Fuchstanzstr.","65"],
  ["Fuchstanzstr.","61"],
  ["Fuchstanzstr.","61"],
  ["Fuchstanzstr.","59"],
  ["Fuchstanzstr.","57"],
  ["Fuchstanzstr.","55"],
  ["Fuchstanzstr.","55"],
  ["Fuchstanzstr.","53"],
  ["Fuchstanzstr.","51"],
  ["Fuchstanzstr.","49"],
  ["Fuchstanzstr.","47"],
  ["Fuchstanzstr.","45"],
  ["Fuchstanzstr.","48"],
  ["Fuchstanzstr.","50"],
  ["Fuchstanzstr.","52"],
  ["Fuchstanzstr.","54"],
  ["Fuchstanzstr.","60a"],
  ["Fuchstanzstr.","60"],
  ["Fuchstanzstr.","60b"],
  ["Fuchstanzstr.","60c"],
  ["Fuchstanzstr.","60d"],
  ["Fuchstanzstr.","56"],
  ["Fuchstanzstr.","58"],
  ["Fuchstanzstr.","58"],
  ["Fuchstanzstr.","64"],
  ["Fuchstanzstr.","66"],
  ["Fuchstanzstr.","68"],
  ["Fuchstanzstr.","70"],
  ["Reifenberger Str.","51"],
  ["Reifenberger Str.","49"],
  ["Reifenberger Str.","47"],
  ["Reifenberger Str.","50"],
  ["Reifenberger Str.","48"],
  ["Reifenberger Str.","46"],
  ["Reifenberger Str.","45"],
  ["Reifenberger Str.","43"],
  ["Reifenberger Str.","41"],
  ["Reifenberger Str.","44"],
  ["Reifenberger Str.","42"],
  ["Reifenberger Str.","40"],
  ["Niddagaustr.","60"],
  ["Niddagaustr.","58"],
  ["Niddagaustr.","56"],
  ["Niddagaustr.","54"],
  ["Niddagaustr.","42"],
  ["Niddagaustr.","40"],
  ["Niddagaustr.","34"],
  ["Niddagaustr.","32"],
  ["Niddagaustr.","30"],
  ["Niddagaustr.","27"],
  ["Niddagaustr.","29"],
  ["Niddagaustr.","31"],
  ["Niddagaustr.","31a"],
  ["Niddagaustr.","33"],
  ["Niddagaustr.","35a"],
  ["Niddagaustr.","35"],
  ["Niddagaustr.","37d"],
  ["Niddagaustr.","37e"],
  ["Niddagaustr.","37c"],
  ["Niddagaustr.","37b"],
  ["Niddagaustr.","37a"],
  ["Niddagaustr.","37"],
  ["Niddagaustr.","39"],
  ["Niddagaustr.","41"],
  ["Niddagaustr.","41a"],
  ["Niddagaustr.","43"],
  ["Niddagaustr.","43"],
  ["Niddagaustr.","53"],
  ["Niddagaustr.","55"],
  ["Niddagaustr.","57"],
  ["Niddagaustr.","59"],
  ["Niddagaustr.","61"],
  ["Niddagaustr.","63"],
  ["Niddagaustr.","76"],
  ["Niddagaustr.","68"],
  ["Niddagaustr.","70"],
  ["Niddagaustr.","66"],
  ["Reifenberger Str.","38"],
  ["Reifenberger Str.","36"],
  ["Reifenberger Str.","34"],
  ["Alexanderstr.","85"],
  ["Reifenberger Str.","39"],
  ["Reifenberger Str.","21"],
  ["Alexanderstr.","98"],
  ["Alexanderstr.","98"],
  ["Alexanderstr.","98"],
  ["Reifenberger Str.","30"],
  ["Reifenberger Str.","28"],
  ["Reifenberger Str.","26"],
  ["Reifenberger Str.","24"],
  ["Reifenberger Str.","22"],
  ["Thudichumstr.","39"],
  ["Thudichumstr.","37"],
  ["Thudichumstr.","35"],
  ["Thudichumstr.","33"],
  ["Thudichumstr.","31"],
  ["Thudichumstr.","17"],
  ["Thudichumstr.","15"],
  ["Thudichumstr.","13"],
  ["Thudichumstr.","18-22"],
  ["Thudichumstr.","18-22"],
  ["Thudichumstr.","18-22"],
  ["Thudichumstr.","18-22"],
  ["Thudichumstr.","18-22"],
  ["Trümperstr.","1"],
  ["Trümperstr.","2"],
  ["Trümperstr.","4"],
  ["Trümperstr.","6"],
  ["Trümperstr.","8"],
  ["Trümperstr.","10"],
  ["Thudichumstr.","32"],
  ["Thudichumstr.","34"],
  ["Thudichumstr.","36"],
  ["Josef-May-Str.","11"],
  ["Josef-May-Str.","9"],
  ["Josef-May-Str.","7"],
  ["Josef-May-Str.","7"],
  ["Josef-May-Str.","5"],
  ["Josef-May-Str.","5"],
  ["Josef-May-Str.","3"],
  ["Josef-May-Str.","1"],
  ["Josef-May-Str.","2"],
  ["Josef-May-Str.","4"],
  ["Josef-May-Str.","6"],
  ["Josef-May-Str.","10"],
  ["Thudichumstr.","38"],
  ["Thudichumstr.","40"],
  ["Thudichumstr.","42"],
  ["Thudichumstr.","40a"],
  ["Thudichumstr.","38a"],
  ["Thudichumstr.","44"],
  ["Thudichumstr.","46"],
  ["Thudichumstr.","48"],
  ["Thudichumstr.","50"],
  ["Thudichumstr.","50"],
  ["Reifenberger Str.","13"],
  ["Reifenberger Str.","13"],
  ["Reifenberger Str.","11"],
  ["Reifenberger Str.","10"],
  ["Hausener Weg","2"],
  ["Hausener Weg","4"],
  ["Hausener Weg","6"],
  ["Hausener Weg","8"],
  ["Hausener Weg","10"],
  ["Hausener Weg","1"],
  ["Hausener Weg","3"],
  ["Hausener Weg","5"],
  ["Hausener Weg","7"],
  ["Niddagaustr.","74"],
  ["Niddagaustr.","74"],
  ["Niddagaustr.","72"],
  ["Hausener Weg","15"],
  ["Hausener Weg","13"],
  ["Hausener Weg","11"],
  ["Hausener Weg","9"],
  ["Hausener Weg","12"],
  ["Hausener Weg","14"],
  ["Hausener Weg","16"],
  ["Hausener Weg","18"],
  ["Hausener Weg","20"],
  ["Hausener Weg","22"],
  ["Hausener Weg","24"],
  ["Hausener Weg","26"],
  ["Hausener Weg","28"],
  ["Hausener Weg","30"],
  ["Hattsteiner Str.","2"],
  ["Hattsteiner Str.","1"],
  ["Hattsteiner Str.","3"],
  ["Hattsteiner Str.","5"],
  ["Hattsteiner Str.","7"],
  ["Hattsteiner Str.","9"],
  ["Hattsteiner Str.","11"],
  ["Hattsteiner Str.","13"],
  ["Hattsteiner Str.","15"],
  ["Hattsteiner Str.","14"],
  ["Hattsteiner Str.","12"],
  ["Hattsteiner Str.","10"],
  ["Alexanderstr.","87"],
  ["Alexanderstr.","89"],
  ["Alexanderstr.","91"],
  ["Alexanderstr.","126"],
  ["Alexanderstr.","124"],
  ["Alexanderstr.","122"],
  ["Hattsteiner Str.","8"],
  ["Hattsteiner Str.","6"],
  ["Hattsteiner Str.","4"],
  ["Hausener Weg","17a"],
  ["Hausener Weg","17"],
  ["Hausener Weg","19"],
  ["Hausener Weg","19"],
  ["Hausener Weg","21"],
  ["Hausener Weg","23"],
  ["Hausener Weg","32"],
  ["Hausener Weg","34"],
  ["Hausener Weg","36"],
  ["Hausener Weg","38"],
  ["Hausener Weg","40"],
  ["Hausener Weg","42"],
  ["Hausener Weg","44"],
  ["Hausener Weg","46"],
  ["Hausener Weg","48"],
  ["Hausener Weg","50"],
  ["Hausener Weg","52"],
  ["Hausener Weg","54"],
  ["Hausener Weg","56"],
  ["Hausener Weg","58"],
  ["Hausener Weg","60"],
  ["Schmittener Str.","2"],
  ["Hausener Weg","80"],
  ["Hausener Weg","82"],
  ["Hausener Weg","84"],
  ["Hausener Weg","86"],
  ["Hausener Weg","86"],
  ["Hausener Weg","88"],
  ["Hausener Weg","88a"],
  ["Hausener Weg","90"],
  ["Hausener Weg","90"],
  ["Hausener Weg","90"],
  ["Hausener Weg","92"],
  ["Hausener Weg","94"],
  ["Hausener Weg","96"],
  ["Hausener Weg","98"],
  ["Ludwig-Landmann-Str.","316"],
  ["Ludwig-Landmann-Str.","318"],
  ["Ludwig-Landmann-Str.","320"],
  ["Ludwig-Landmann-Str.","322"],
  ["Ludwig-Landmann-Str.","324"],
  ["Ludwig-Landmann-Str.","326"]
];

const GANGFOLGE_06_ALIASES = {
  "ludwig-landmann-strasse":"Ludwig-Landmann-Str.","ludwig-landmann-str":"Ludwig-Landmann-Str.",
  "landmannstrasse":"Ludwig-Landmann-Str.","landmannstr":"Ludwig-Landmann-Str.",
  "ludwig landmann":"Ludwig-Landmann-Str.",
  "stephan-heise-strasse":"Stephan-Heise-Str.","stephan-heise-str":"Stephan-Heise-Str.",
  "stephan heise":"Stephan-Heise-Str.","heise":"Stephan-Heise-Str.",
  "westring":"Westring",
  "hausener weg":"Hausener Weg","hausener":"Hausener Weg",
  "schmittener strasse":"Schmittener Str.","schmittener str":"Schmittener Str.","schmittener":"Schmittener Str.",
  "niddagaustrasse":"Niddagaustr.","niddagaustr":"Niddagaustr.","niddagau":"Niddagaustr.",
  "alexanderstrasse":"Alexanderstr.","alexanderstr":"Alexanderstr.",
  "seelenberger strasse":"Seelenberger Str.","seelenberger str":"Seelenberger Str.","seelenberger":"Seelenberger Str.",
  "fuchstanzstrasse":"Fuchstanzstr.","fuchstanzstr":"Fuchstanzstr.","fuchstanz":"Fuchstanzstr.",
  "hattsteiner strasse":"Hattsteiner Str.","hattsteiner str":"Hattsteiner Str.","hattsteiner":"Hattsteiner Str.",
  "reichenbecher weg":"Reichenbecher Weg","reichenbecher":"Reichenbecher Weg",
  "reinbomer weg":"Reinbomer Weg","reinbomer":"Reinbomer Weg",
  "reifenberger strasse":"Reifenberger Str.","reifenberger str":"Reifenberger Str.","reifenberger":"Reifenberger Str.",
  "kollwitzstrasse":"Kollwitzstr.","kollwitzstr":"Kollwitzstr.","kollwitz":"Kollwitzstr.",
  "gontardstrasse":"Gontardstr.","gontardstr":"Gontardstr.","gontard":"Gontardstr.",
  "thudichumstrasse":"Thudichumstr.","thudichumstr":"Thudichumstr.","thudichumstraße":"Thudichumstr.",
  "trümperstrasse":"Trümperstr.","trümperstr":"Trümperstr.","trümper":"Trümperstr.",
  "josef-may-strasse":"Josef-May-Str.","josef-may-str":"Josef-May-Str.","josef may":"Josef-May-Str.","may":"Josef-May-Str."
};

registerGangfolge({
  name: '60488-06',
  route: GANGFOLGE_06_ROUTE,
  aliases: GANGFOLGE_06_ALIASES
});
